name: Add Issue to main Project

on:
  issues:
    types:
      - opened

jobs:
  track_issue:
    runs-on: cg-linux
    steps:
    # Generate token for GitHub app
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1
        with:
          app-id: 1008511
          private-key: ${{ secrets.CG_ISSUE_PROCESSOR_TOKEN }}

    # Add the issue to the project
      - name: Add issue to project
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PROJECT_ID: 3
          ISSUE_ID: ${{ github.event.issue.number }}
        run: |
          gh project item-add $PROJECT_ID --owner Catglobe --url https://github.com/$GITHUB_REPOSITORY/issues/$ISSUE_ID

